import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, paddingBottom: 40 },
  header: {
    backgroundColor: colors.primary,
    borderRadius: radii.xl,
    padding: 22,
    marginBottom: 14,
    ...shadow.lift,
  },
  headerEyebrow: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    fontFamily: fonts.body,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: "#fff",
    marginTop: 4,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.55)",
    fontFamily: fonts.body,
    marginTop: 5,
    fontSize: 13,
  },
  scanButton: {
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "#9FE1CB",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: radii.lg,
    marginBottom: 12,
    alignItems: "center",
  },
  scanButtonText: {
    color: "#085041",
    fontWeight: "700",
    fontFamily: fonts.body,
    fontSize: 15,
  },
  scanButtonSub: {
    color: "#0F6E56",
    fontFamily: fonts.body,
    fontSize: 11,
    marginTop: 3,
  },
  scanMessage: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginBottom: 10,
    fontSize: 13,
    textAlign: "center",
  },
  receipt: {
    width: "100%",
    height: 180,
    borderRadius: radii.md,
    marginBottom: 12,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadow.soft,
  },
  input: {
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: radii.md,
    padding: 14,
    marginBottom: 10,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.body,
    color: colors.text,
    fontSize: 15,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    fontFamily: fonts.body,
    marginBottom: 8,
    color: colors.textMuted,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    fontFamily: fonts.heading,
    marginBottom: 10,
    color: colors.text,
  },
  pillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  pill: {
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 13,
    paddingVertical: 7,
    backgroundColor: colors.surfaceMuted,
  },
  pillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  pillText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  pillTextActive: { color: "#fff" },
  limitText: {
    color: colors.textMuted,
    marginBottom: 6,
    fontFamily: fonts.mono,
    fontSize: 11,
  },
  suggestionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FAEEDA",
    borderWidth: 0.5,
    borderColor: "#FAC775",
    borderRadius: radii.md,
    padding: 10,
    marginTop: 4,
  },
  suggestionText: {
    color: "#633806",
    fontFamily: fonts.body,
    fontSize: 12,
  },
  suggestionButton: {
    backgroundColor: "#FAC775",
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  suggestionButtonText: {
    color: "#412402",
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 12,
  },
  lineItemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  lineItemName: { flex: 1, marginBottom: 0, marginRight: 8 },
  lineItemAmount: { width: 90, marginBottom: 0, marginRight: 8 },
  lineItemRemove: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 0.5,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: radii.md,
  },
  lineItemRemoveText: {
    color: colors.danger,
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 13,
  },
  secondaryButton: {
    backgroundColor: colors.surfaceMuted,
    padding: 12,
    borderRadius: radii.md,
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: colors.border,
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: "600",
    fontFamily: fonts.body,
    fontSize: 14,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: radii.md,
    alignItems: "center",
    marginTop: 4,
    ...shadow.soft,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontFamily: fonts.body,
    fontSize: 15,
  },
  error: {
    color: colors.danger,
    marginBottom: 10,
    fontFamily: fonts.body,
    fontSize: 13,
  },
  helperText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginBottom: 10,
  },
  cameraContainer: { flex: 1, backgroundColor: "#000" },
  camera: { flex: 1 },
  cameraActions: { padding: 16, backgroundColor: "#000" },
  cameraButton: {
    backgroundColor: "#fff",
    padding: 14,
    borderRadius: radii.md,
    alignItems: "center",
    marginBottom: 8,
  },
  cameraButtonSecondary: {
    backgroundColor: "#333",
    padding: 14,
    borderRadius: radii.md,
    alignItems: "center",
  },
  cameraButtonText: {
    color: "#000",
    fontWeight: "700",
    fontFamily: fonts.body,
  },
  permissionContainer: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  permissionText: {
    fontSize: 15,
    marginBottom: 16,
    fontFamily: fonts.body,
    color: colors.text,
  },
});
