import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, paddingTop: 16 },
  header: {
    backgroundColor: colors.primary,
    borderRadius: radii.xl,
    padding: 24,
    marginBottom: 14,
    ...shadow.lift,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerEyebrow: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 10,
    letterSpacing: 1.5,
    fontFamily: fonts.body,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: "#fff",
    marginTop: 4,
  },
  scanButtonCompact: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.accentSoft,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 6,
  },
  scanButtonCompactText: {
    color: colors.accent,
    fontWeight: "700",
    fontFamily: fonts.body,
    fontSize: 13,
  },
  scanMessageBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.accentSecondaryS,
    borderRadius: radii.md,
    padding: 12,
    marginBottom: 12,
    gap: 8,
  },
  scanMessage: {
    color: colors.accentSecondary,
    fontFamily: fonts.body,
    fontSize: 13,
    flex: 1,
  },
  receipt: {
    width: "100%",
    height: 160,
    borderRadius: radii.md,
    marginBottom: 12,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadow.soft,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    fontFamily: fonts.heading,
    marginBottom: 14,
    color: colors.text,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  currencySymbolLarge: {
    fontSize: 26,
    fontWeight: "700",
    color: colors.textMuted,
    fontFamily: fonts.heading,
    marginRight: 6,
  },
  amountInput: {
    flex: 1,
    fontSize: 28,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: colors.text,
    paddingVertical: 16,
  },
  input: {
    borderRadius: radii.md,
    padding: 14,
    marginBottom: 10,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.body,
    color: colors.text,
    fontSize: 14,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    fontFamily: fonts.body,
    marginBottom: 8,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  pillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  pill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.surfaceMuted,
  },
  pillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  pillText: { color: colors.text, fontFamily: fonts.body, fontWeight: "600", fontSize: 13 },
  pillTextActive: { color: "#fff" },
  rateNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
    backgroundColor: colors.accentSecondaryS,
    borderRadius: radii.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  rateNoticeText: {
    color: colors.accentSecondary,
    fontFamily: fonts.mono,
    fontSize: 12,
  },
  budgetInline: { marginBottom: 12 },
  budgetInlineRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  budgetInlineLabel: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.body },
  budgetInlineValue: { color: colors.text, fontSize: 11, fontFamily: fonts.mono, fontWeight: "600" },
  progressTrack: { height: 5, backgroundColor: colors.surfaceMuted, borderRadius: radii.pill, overflow: "hidden", marginBottom: 4 },
  progressFill: { height: 5, borderRadius: radii.pill },
  suggestionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFF8E6",
    borderWidth: 0.5,
    borderColor: "#FFD980",
    borderRadius: radii.md,
    padding: 10,
    marginBottom: 10,
  },
  suggestionText: { color: "#7A5500", fontFamily: fonts.body, fontSize: 12, flex: 1 },
  suggestionButton: {
    backgroundColor: "#FFD980",
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  suggestionButtonText: { color: "#4A3700", fontFamily: fonts.body, fontWeight: "700", fontSize: 12 },
  addCategoryToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
  },
  addCategoryToggleText: { color: colors.textMuted, fontFamily: fonts.body, fontSize: 13 },
  newCategoryBox: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 12,
    marginTop: 4,
  },
  receiptRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 12,
  },
  receiptLabel: {
    width: 60,
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 13,
    fontWeight: "600",
  },
  receiptInput: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 12,
    fontFamily: fonts.mono,
    color: colors.text,
    fontSize: 14,
  },
  receiptInputTotal: {
    fontWeight: "700",
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  lineItemRow: { flexDirection: "row", alignItems: "center", marginBottom: 8, gap: 8 },
  lineItemName: { flex: 1, marginBottom: 0 },
  lineItemAmount: { width: 90, marginBottom: 0 },
  lineItemRemove: {
    backgroundColor: "#FFF0F0",
    borderWidth: 1,
    borderColor: "#FFD0D0",
    padding: 12,
    borderRadius: radii.md,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButton: {
    flexDirection: "row",
    backgroundColor: colors.surfaceMuted,
    padding: 13,
    borderRadius: radii.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.5,
    borderColor: colors.border,
    marginTop: 4,
  },
  secondaryButtonText: { color: colors.textMuted, fontWeight: "600", fontFamily: fonts.body, fontSize: 14 },
  errorBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF0F0",
    borderRadius: radii.md,
    padding: 12,
    marginBottom: 10,
  },
  error: { color: colors.danger, fontFamily: fonts.body, fontSize: 13, flex: 1 },
  primaryButton: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    padding: 18,
    borderRadius: radii.lg,
    alignItems: "center",
    justifyContent: "center",
    ...shadow.lift,
  },
  primaryButtonText: { color: "#fff", fontWeight: "700", fontFamily: fonts.body, fontSize: 16 },
  successToast: {
    position: "absolute",
    top: 56,
    left: 20,
    right: 20,
    zIndex: 100,
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    ...shadow.lift,
  },
  successToastText: { color: "#fff", fontFamily: fonts.body, fontWeight: "700", fontSize: 14, flex: 1 },
  cameraContainer: { flex: 1, backgroundColor: "#000" },
  camera: { flex: 1 },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraFrame: {
    width: 260,
    height: 180,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.6)",
    borderRadius: radii.md,
  },
  cameraActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 24,
    paddingBottom: 40,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  captureButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  captureInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#fff",
  },
  cameraButtonSecondary: {
    width: 80,
    alignItems: "center",
    gap: 4,
  },
  cameraButtonText: { color: "#fff", fontFamily: fonts.body, fontWeight: "600", fontSize: 12 },
  permissionContainer: { flex: 1, padding: 32, justifyContent: "center", alignItems: "center", backgroundColor: colors.background },
  permissionText: { fontSize: 15, marginBottom: 20, fontFamily: fonts.body, color: colors.text, textAlign: "center" },
});
