import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    borderRadius: radii.xl,
    padding: 24,
    marginBottom: 14,
    ...shadow.lift,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerEyebrow: {
    color: colors.accent,
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily: fonts.body,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 22,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginTop: 2,
  },
  headerBadge: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  headerBadgeText: {
    color: "#fff",
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  headerTotal: {
    color: "#fff",
    fontSize: 32,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginTop: 12,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.5)",
    fontFamily: fonts.body,
    marginTop: 4,
    fontSize: 12,
  },
  heroPillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 12,
  },
  heroPill: {
    borderRadius: radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 0.5,
  },
  heroPillText: {
    fontSize: 11,
    fontWeight: "600",
    fontFamily: fonts.body,
  },
  heroPillGood: {
    backgroundColor: "rgba(0,212,106,0.15)",
    borderColor: "rgba(0,212,106,0.3)",
  },
  heroPillTextGood: { color: colors.accent },
  heroPillWarn: {
    backgroundColor: "rgba(239,159,39,0.15)",
    borderColor: "rgba(239,159,39,0.3)",
  },
  heroPillTextWarn: { color: "#EF9F27" },
  heroPillDanger: {
    backgroundColor: "rgba(226,75,74,0.15)",
    borderColor: "rgba(226,75,74,0.3)",
  },
  heroPillTextDanger: { color: colors.danger },
  statRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: 14,
    borderWidth: 0.5,
    borderColor: colors.border,
    ...shadow.soft,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "700",
    fontFamily: fonts.heading,
    color: colors.text,
  },
  statSub: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginTop: 2,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: radii.md,
    padding: 14,
    marginBottom: 10,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.body,
    color: colors.text,
    fontSize: 14,
  },
  chartCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 14,
    ...shadow.soft,
  },
  filterCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 14,
    ...shadow.soft,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
    gap: 6,
  },
  filterPill: {
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.surfaceMuted,
  },
  filterPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  filterTextActive: { color: "#fff" },
  budgetCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 20,
    ...shadow.soft,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginBottom: 12,
    color: colors.text,
  },
  listHeader: {
    fontSize: 15,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 10,
  },
  budgetRow: { marginBottom: 12 },
  budgetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  budgetName: {
    fontFamily: fonts.body,
    fontWeight: "600",
    color: colors.text,
    fontSize: 13,
  },
  budgetAmount: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.textMuted,
  },
  progressTrack: {
    height: 4,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.pill,
    overflow: "hidden",
  },
  progressFill: {
    height: 4,
    borderRadius: radii.pill,
  },
  budgetWarning: {
    marginTop: 3,
    fontFamily: fonts.body,
    fontSize: 11,
  },
  axisText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 10,
  },
  pieCenter: {
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: colors.text,
    fontSize: 13,
  },
  list: { marginTop: 0 },
  emptyContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  empty: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 13,
  },
});
