import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, paddingTop: 16, paddingHorizontal: 16 },
  contentContainer: { paddingBottom: 140 },
  header: {
    backgroundColor: colors.primary,
    borderRadius: radii.xl,
    padding: 24,
    marginBottom: 14,
    ...shadow.lift,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  headerEyebrow: {
    color: colors.accent,
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily: fonts.body,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 20,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginTop: 2,
  },
  headerBadge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.15)",
  },
  headerBadgeText: {
    color: "rgba(255,255,255,0.8)",
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  headerTotal: {
    color: "#fff",
    fontSize: 36,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginTop: 16,
    letterSpacing: -1,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.45)",
    fontFamily: fonts.body,
    marginTop: 4,
    fontSize: 12,
  },
  heroPillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 14,
  },
  heroPill: {
    borderRadius: radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 0.5,
  },
  heroPillText: {
    fontSize: 11,
    fontWeight: "600",
    fontFamily: fonts.body,
  },
  heroPillGood: {
    backgroundColor: "rgba(0,201,107,0.15)",
    borderColor: "rgba(0,201,107,0.3)",
  },
  heroPillTextGood: { color: colors.accent },
  heroPillWarn: {
    backgroundColor: "rgba(255,159,10,0.15)",
    borderColor: "rgba(255,159,10,0.3)",
  },
  heroPillTextWarn: { color: colors.warning },
  heroPillDanger: {
    backgroundColor: "rgba(255,59,59,0.15)",
    borderColor: "rgba(255,59,59,0.3)",
  },
  heroPillTextDanger: { color: colors.danger },
  statRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    ...shadow.soft,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    fontFamily: fonts.heading,
    color: colors.text,
  },
  statSub: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginTop: 2,
  },
  searchInput: {
    borderRadius: radii.md,
    padding: 13,
    marginBottom: 12,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.body,
    color: colors.text,
    fontSize: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chartCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadow.soft,
  },
  filterCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadow.soft,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
    gap: 6,
  },
  filterPill: {
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: colors.surfaceMuted,
  },
  filterPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  filterTextActive: { color: "#fff" },
  budgetCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 14,
    ...shadow.soft,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginBottom: 14,
    color: colors.text,
    letterSpacing: 0.2,
  },
  listHeader: {
    fontSize: 14,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  budgetRow: { marginBottom: 14 },
  budgetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  budgetName: {
    fontFamily: fonts.body,
    fontWeight: "700",
    color: colors.text,
    fontSize: 13,
  },
  budgetAmount: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.textMuted,
  },
  progressTrack: {
    height: 5,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.pill,
    overflow: "hidden",
  },
  progressFill: {
    height: 5,
    borderRadius: radii.pill,
  },
  budgetWarning: {
    marginTop: 4,
    fontFamily: fonts.body,
    fontSize: 11,
    fontWeight: "600",
  },
  axisText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 10,
  },
  pieCenter: {
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: colors.text,
    fontSize: 13,
  },
  list: { marginTop: 0 },
  quickActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  quickActionCard: {
    flexBasis: "48%",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 10,
    ...shadow.soft,
  },
  quickActionLabel: {
    color: colors.text,
    fontFamily: fonts.body,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  emptyContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  empty: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 13,
    textAlign: "center",
  },
  emptyIcon: {
    marginBottom: 10,
  },
  chartsContainer: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 14,
    marginTop: 12,
    ...shadow.soft,
  },
  chartsTitle: {
    marginBottom: 14,
  },
  chartsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  chartThumbnail: {
    flexBasis: "48%",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    borderWidth: 0.5,
    borderColor: colors.border,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 150,
  },
  chartThumbnailTitle: {
    fontSize: 11,
    fontWeight: "700",
    fontFamily: fonts.heading,
    color: colors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  chartExpandedContainer: {
    paddingVertical: 12,
  },
  chartExpandedTitle: {
    fontSize: 16,
    fontWeight: "700",
    fontFamily: fonts.heading,
    color: colors.text,
    marginBottom: 16,
    marginTop: 8,
  },
  closeChartsButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    borderWidth: 0.5,
    borderColor: colors.border,
  },
  closeChartsText: {
    color: colors.primary,
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 13,
  },
});