import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  topSection: {
    paddingHorizontal: 28,
    paddingTop: 80,
    paddingBottom: 32,
  },
  glow: {
    position: "absolute",
    top: -80,
    right: -60,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "rgba(0, 201, 107, 0.10)",
  },
  glowSecondary: {
    position: "absolute",
    top: 40,
    left: -80,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(0, 153, 255, 0.07)",
  },
  appName: {
    fontFamily: fonts.body,
    color: colors.accent,
    letterSpacing: 2,
    textTransform: "uppercase",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 14,
  },
  heroTitle: {
    fontSize: 34,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: "#fff",
    lineHeight: 40,
  },
  heroSub: {
    color: "rgba(255,255,255,0.45)",
    fontFamily: fonts.body,
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
  },
  cardWrapper: {
    flex: 1,
    justifyContent: "flex-start",
    paddingHorizontal: 20,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    padding: 24,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.1)",
    ...shadow.lift,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
    paddingHorizontal: 14,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontFamily: fonts.body,
    color: colors.text,
    fontSize: 15,
  },
  roleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 10,
  },
  roleButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: colors.surfaceMuted,
  },
  roleButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  roleText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 14,
  },
  roleTextActive: {
    color: "#fff",
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: radii.md,
    alignItems: "center",
    marginTop: 6,
    ...shadow.soft,
  },
  primaryButtonText: {
    color: colors.primary,
    fontWeight: "700",
    fontFamily: fonts.body,
    fontSize: 16,
    letterSpacing: 0.2,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
    gap: 10,
  },
  dividerLine: {
    flex: 1,
    height: 0.5,
    backgroundColor: colors.border,
  },
  dividerText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  link: {
    alignItems: "center",
    marginTop: 16,
  },
  linkText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 13,
  },
  linkAction: {
    color: colors.accent,
    fontWeight: "700",
  },
  guestButton: {
    backgroundColor: "transparent",
    paddingVertical: 14,
    borderRadius: radii.md,
    alignItems: "center",
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  guestButtonText: {
    color: colors.text,
    fontWeight: "700",
    fontFamily: fonts.body,
    fontSize: 15,
  },
});