import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadow } from "../../utils/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, paddingBottom: 120 },
  header: {
    backgroundColor: colors.primary,
    borderRadius: radii.xl,
    padding: 22,
    marginBottom: 14,
    ...shadow.lift,
  },
  headerEyebrow: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 10,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    fontFamily: fonts.body,
    fontWeight: "700",
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: fonts.heading,
    fontWeight: "700",
    color: "#fff",
    marginTop: 6,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.5)",
    fontFamily: fonts.body,
    marginTop: 5,
    fontSize: 13,
  },
  headerStatsRow: {
    flexDirection: "row",
    marginTop: 18,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: radii.md,
    padding: 14,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  headerStat: { flex: 1, alignItems: "center" },
  headerStatLabel: {
    color: "rgba(255,255,255,0.45)",
    fontFamily: fonts.body,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
  },
  headerStatValue: {
    color: "#fff",
    fontFamily: fonts.heading,
    fontWeight: "700",
    fontSize: 20,
    marginTop: 4,
  },
  headerStatDivider: {
    width: 0.5,
    backgroundColor: "rgba(255,255,255,0.12)",
    marginHorizontal: 8,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    borderWidth: 0.5,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadow.soft,
  },
  cardTitle: {
    fontSize: 14,
    fontFamily: fonts.heading,
    fontWeight: "700",
    marginBottom: 14,
    color: colors.text,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  detailLabel: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 14,
  },
  detailValue: {
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 14,
  },
  roleBadge: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 0.5,
    borderColor: colors.border,
  },
  roleBadgeAdmin: {
    backgroundColor: colors.accentSoft,
    borderColor: "#8FD9C0",
  },
  roleBadgeText: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 12,
  },
  roleBadgeTextAdmin: { color: "#085041" },
  fieldLabel: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 11,
    marginTop: 12,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
  },
  input: {
    borderRadius: radii.md,
    padding: 14,
    marginBottom: 8,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.mono,
    color: colors.text,
    fontSize: 15,
    borderWidth: 1,
    borderColor: colors.border,
  },
  helperText: {
    marginTop: 4,
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
    lineHeight: 17,
  },
  pillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  pill: {
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.surfaceMuted,
  },
  pillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  pillText: {
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 12,
  },
  pillTextActive: { color: "#fff" },
  rateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  rateLabel: {
    width: 44,
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 13,
  },
  rateInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: 11,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.mono,
    color: colors.text,
    fontSize: 14,
  },
  rateUnit: {
    color: colors.textMuted,
    fontFamily: fonts.body,
    fontSize: 12,
    width: 36,
  },
  fetchRatesButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentSoft,
    borderRadius: radii.md,
    paddingVertical: 10,
    marginTop: 8,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#8FD9C0",
    gap: 6,
  },
  fetchRatesButtonText: {
    color: "#085041",
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 13,
  },
  cardDescription: {
    fontSize: 12,
    color: colors.textMuted,
    fontFamily: fonts.body,
    marginTop: -8,
    marginBottom: 16,
    lineHeight: 18,
  },
  budgetRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  budgetLabel: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.body,
    fontWeight: "600",
    fontSize: 14,
  },
  budgetInput: {
    width: 120,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: 11,
    backgroundColor: colors.surfaceMuted,
    fontFamily: fonts.mono,
    color: colors.text,
    fontSize: 14,
    textAlign: "right",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFF0F0",
    borderWidth: 1,
    borderColor: "#FFD0D0",
    borderRadius: radii.lg,
    padding: 16,
    marginBottom: 12,
  },
  logoutButtonText: {
    color: colors.danger,
    fontFamily: fonts.body,
    fontWeight: "700",
    fontSize: 15,
  },
});